author: airtasker
name: prepare-repository
description: Prepare the repository for building and testing.

runs:
  using: composite

  steps:
  - uses: actions/checkout@v5

  - uses: pnpm/action-setup@v4

  - name: Setup Node.js
    uses: actions/setup-node@v5
    with:
      cache: 'pnpm'

  - name: Install dependencies
    run: pnpm install --frozen-lockfile
    shell: bash