# syntax=docker/dockerfile:1

# Packages the Spot CLI so consumers need Docker rather than a Node toolchain and a
# node_modules beside their contracts.
#
# Run it against a bind-mounted workspace:
#
#   docker run --rm --user "$(id -u):$(id -g)" \
#     --volume "$PWD:$PWD" --workdir "$PWD" \
#     ghcr.io/airtasker/spot:<version> \
#     generate -c api.ts -g openapi3 -l yaml -o doc/output
#
# Path arguments reach the filesystem unresolved, so they are interpreted relative to
# the working directory inside the container. Mounting the workspace at its real
# absolute path keeps every path argument resolving the same way inside and outside.
# `-o ~/x` is the exception that cannot: a tilde expands against the container's home.
#
# `--user` matters beyond file ownership. Output must be owned by the invoking user:
# downstream builds key caches and incremental task inputs on its mtime, and output
# they cannot overwrite stalls them (e.g. rails-monolith's RSpec boot, bff-client's
# Gradle codegen).
#
# No `.npmrc` is copied in: nothing in Spot's dependency tree is @airtasker-scoped, so
# the image builds with no registry credential at all.
#
# The `node` tag tracks the `nodejs` line in .tool-versions, and the corepack pin
# tracks `packageManager` in package.json. Keep all three in step.

FROM node:22.22.1-bookworm-slim AS base
WORKDIR /opt/spot
RUN corepack enable && corepack prepare pnpm@10.28.1 --activate
# docs/package.json is a workspace member, so --frozen-lockfile refuses to install
# without it. Its own dependencies are all devDependencies, so no webpack or redoc
# reaches the prod-deps stage below.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY docs/package.json ./docs/package.json

# Runtime dependencies only. Resolved in its own stage rather than by pruning the
# build stage, so the compiler and the test toolchain never reach the final image.
FROM base AS prod-deps
RUN pnpm install --frozen-lockfile --prod

FROM base AS builder
RUN pnpm install --frozen-lockfile
COPY tsconfig.json index.ts ./
COPY lib ./lib
COPY cli ./cli
# `tsc` rather than the pack lifecycle. `prepack` also runs `oclif-dev manifest` — the
# image must ship no manifest, see the runtime stage — and `pnpm build-docs`, a
# webpack/redoc bundle needing --openssl-legacy-provider that this image never serves.
RUN pnpm exec tsc

FROM node:22.22.1-bookworm-slim AS runtime
WORKDIR /opt/spot
COPY --from=prod-deps /opt/spot/node_modules ./node_modules
COPY --from=builder /opt/spot/build ./build
COPY bin ./bin
# oclif discovers commands by scanning the `oclif.commands` directory relative to the
# nearest package.json, so package.json, bin/ and build/ have to keep these relative
# positions. This image ships no oclif.manifest.json — the scan costs a few
# milliseconds — which is what makes deleting a command file below actually remove the
# command. The npm package does ship one, generated by `prepack`, where the same
# deletion would not.
COPY package.json ./

# mock, docs and init are npm-only: mock and docs serve long-running local dev servers,
# and init scaffolds a project on the host. Removing the compiled files removes the
# commands, because there is no manifest that could still advertise them.
# Asserted before removal: `rm -f` succeeds on a path that does not exist, so if the
# emitted layout ever moves this would silently ship the three commands instead.
RUN for c in mock docs init; do \
      test -f "build/cli/src/commands/$c.js" \
        || { echo "expected build/cli/src/commands/$c.js — emitted layout moved" >&2; exit 1; }; \
      rm -f "build/cli/src/commands/$c".*; \
    done

# Load-bearing, and not a convenience. Spot is meant to be run with
# `--user "$(id -u):$(id -g)"`, which names a uid with no /etc/passwd entry, so
# `os.homedir()` returns `/`. oclif writes an error log under the home directory
# before it exits, that mkdir fails with EACCES, and the throw inside the error
# handler pre-empts the exit code — so every failing command exits 0. `spot validate`
# would report an invalid contract and still pass its CI gate. /tmp because an
# arbitrary uid has to be able to write it.
ENV HOME=/tmp

# Overridden by `--workdir` in normal use. Mode 1777 because the documented invocation
# passes an arbitrary `--user`, which would otherwise find this directory unwritable;
# and `USER node` so that a bare `docker run` with no `--user` does not write output as
# root, which is the ownership problem described at the top of this file.
RUN mkdir -p /workspace && chmod 1777 /workspace
USER node
WORKDIR /workspace
ENTRYPOINT ["node", "/opt/spot/bin/run"]
